// This file was AUTOMATICALLY GENERATED by dbg-import (smuggol) for github.com/robertkrimen/dbg

package otto

import (
	Dbg "github.com/glycerine/dynamic-go/backend/dbg"
)

var dbg, dbgf = Dbg.New()
